# Generated by Django 3.2.2 on 2024-07-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='inventoried',
            field=models.BooleanField(default=False, verbose_name='¿Es inventariado?'),
        ),
    ]
